// <auto-generated />
using System;
using Basisregisters.IntegrationDb.Reporting.SuspiciousCases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Basisregisters.IntegrationDb.Reporting.SuspiciousCases.Migrations
{
    [DbContext(typeof(SuspiciousCaseReportingContext))]
    [Migration("20250527094749_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Basisregisters.IntegrationDb.Reporting.SuspiciousCases.SuspiciousCase", b =>
                {
                    b.Property<string>("NisCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nis_code");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("object_id");

                    b.Property<string>("SuspiciousCaseType")
                        .HasColumnType("text")
                        .HasColumnName("suspicious_case_type");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date")
                        .HasColumnName("date_added");

                    b.Property<DateOnly?>("DateClosed")
                        .HasColumnType("date")
                        .HasColumnName("date_closed");

                    b.Property<string>("ObjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("NisCode", "ObjectId", "SuspiciousCaseType");

                    b.HasIndex("NisCode");

                    b.HasIndex("Status");

                    b.HasIndex("SuspiciousCaseType");

                    b.HasIndex("ObjectId", "ObjectType");

                    b.ToTable("suspicious_cases_reporting", "integration_suspicious_cases");
                });

            modelBuilder.Entity("Basisregisters.IntegrationDb.Reporting.SuspiciousCases.SuspiciousCaseReport", b =>
                {
                    b.Property<string>("NisCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nis_code");

                    b.Property<string>("SuspiciousCaseType")
                        .HasColumnType("text")
                        .HasColumnName("suspicious_case_type");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<int>("ClosedCases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("closed_cases");

                    b.Property<int>("OpenCases")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("open_cases");

                    b.HasKey("NisCode", "SuspiciousCaseType", "Month");

                    b.ToTable("suspicious_case_reports", "integration_suspicious_cases");
                });
#pragma warning restore 612, 618
        }
    }
}
